version: '3.7'

services:

  orders:
    build:
      context: ./services/orders
      dockerfile: Dockerfile
    volumes:
      - './services/orders:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig  # nuevo
      - DATABASE_URL=sqlite:///data.sqlite  # nuevo
      # - DATABASE_TEST_URL=sqlite:////orders_test.sqlite  # nuevo
